language: php

git:
  depth: 1

jobs:
  include:
    - &test
      stage: Test
      php: "7.4"
      os: linux
      install:
        - travis_retry composer self-update
        - travis_retry composer install --no-interaction --prefer-source --dev
      script:
        - composer test
        - composer lint
    - &compatibility
      <<: *test
      stage: Compatibility
      php: "7.1"
    - <<: *compatibility
      php: "7.2"
    - <<: *compatibility
      php: "7.3"
    - <<: *test
      stage: Analyze
      name: Sonarcloud
      dist: trusty
      addons:
        sonarcloud:
          organization: "getyoti"
      if: type == pull_request OR branch = master
      script:
        - composer coverage-clover
        - sonar-scanner
