language: php

git:
  depth: 1

jobs:
  include:
    - &test
      stage: Test
      php: "7.4"
      os: linux
      install:
        - travis_retry composer self-update
        - travis_retry composer install --no-interaction --prefer-source --dev
      script:
        - composer test
        - composer lint
    - &compatibility
      <<: *test
      stage: Compatibility
      php: "7.1"
    - <<: *compatibility
      php: "7.2"
    - <<: *compatibility
      php: "7.3"
    - <<: *compatibility
      php: "8.0snapshot"
      install:
        # Remove php-cs-fixer until compatible with PHP 8
        - travis_retry composer remove --dev --no-interaction friendsofphp/php-cs-fixer
        - travis_retry composer self-update
        - travis_retry composer install --no-interaction --prefer-source --dev
      before_script:
        - echo 'xdebug.mode=coverage' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
      script:
        - composer test
    - <<: *test
      stage: Analyze
      name: Sonarcloud
      dist: trusty
      addons:
        sonarcloud:
          organization: "getyoti"
      if: type == pull_request OR branch = master
      script:
        - composer coverage-clover
        - sonar-scanner
