version: '3'

services:
  app:
    build: https://github.com/getyoti/doc-scan-sandbox-test-app.git#0.2.0
    env_file:
        - ./.env
    environment:
        - YOTI_KEY_FILE_PATH=/usr/src/keys/privateKey.pem
        - YOTI_CLIENT_SDK_ID=${YOTI_SANDBOX_CLIENT_SDK_ID}
        - YOTI_DOC_SCAN_API_URL=${YOTI_DOC_SCAN_API_URL}
    volumes:
        - ${YOTI_KEY_FILE_PATH}:/usr/src/keys/privateKey.pem
    ports:
        - "3000:3000"
    depends_on:
        - selenium

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    volumes:
      - ./resources:/usr/src/resources
    ports:
      - "4444:4444"

  test:
    image: php:7-fpm-alpine
    command: ./vendor/bin/behat --colors
    env_file:
      - ./.env
    environment:
      - YOTI_KEY_FILE_PATH=/usr/src/keys/privateKey.pem
      - YOTI_SANDBOX_CLIENT_SDK_ID=${YOTI_SANDBOX_CLIENT_SDK_ID}
    volumes:
      - ./:/var/www/html
      - ${YOTI_KEY_FILE_PATH}:/usr/src/keys/privateKey.pem
    depends_on:
      - app

  composer:
    image: composer
    volumes:
      - ../../:/app
    working_dir: /app/examples/doc-scan
    command: update
